build:
	gomake -C lib/ build
	gomake -C server/ build
install: build
	gomake -C lib/ install
	gomake -C server/ install
deinstall:
	gomake -C lib/ deinstall
	gomake -C server/ deinstall
clean:
	gomake -C lib/ clean
	gomake -C server/ clean
