build:
	gomake -C lib/ build
	gomake -C ttime/ build
install: build
	gomake -C lib/ install
	gomake -C ttime/ install
deinstall:
	gomake -C lib/ deinstall
	gomake -C ttime/ deinstall
clean:
	gomake -C lib/ clean
	gomake -C ttime/ clean
