build:
	gomake -C dml/ build
	gomake -C liccor/ build
	gomake -C loc/ build
	gomake -C ttime/ build
install: build
	gomake -C dml/ install
	gomake -C liccor/ install
	gomake -C loc/ install
	gomake -C ttime/ install
deinstall:
	gomake -C dml/ deinstall
	gomake -C liccor/ deinstall
	gomake -C loc/ deinstall
	gomake -C ttime/ deinstall
clean:
	gomake -C dml/ clean
	gomake -C liccor/ clean
	gomake -C loc/ clean
	gomake -C ttime/ clean
